//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocaleResources.Core.Contents {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StudentRegistration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StudentRegistration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocaleResources.Core.Contents.StudentRegistration", typeof(StudentRegistration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch.
        /// </summary>
        public static string Batch {
            get {
                return ResourceManager.GetString("Batch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course.
        /// </summary>
        public static string Course {
            get {
                return ResourceManager.GetString("Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Fee.
        /// </summary>
        public static string CourseFee {
            get {
                return ResourceManager.GetString("CourseFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        public static string CourseFeeGrid {
            get {
                return ResourceManager.GetString("CourseFeeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Fee.
        /// </summary>
        public static string DiscountFee {
            get {
                return ResourceManager.GetString("DiscountFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string DiscountFeeGrid {
            get {
                return ResourceManager.GetString("DiscountFeeGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Payment.
        /// </summary>
        public static string DuePayment {
            get {
                return ResourceManager.GetString("DuePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string DuePaymentGrid {
            get {
                return ResourceManager.GetString("DuePaymentGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalment1.
        /// </summary>
        public static string FirstInstallment {
            get {
                return ResourceManager.GetString("FirstInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalments.
        /// </summary>
        public static string Instalments {
            get {
                return ResourceManager.GetString("Instalments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Payment Fine.
        /// </summary>
        public static string LatePaymentFine {
            get {
                return ResourceManager.GetString("LatePaymentFine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Instalment.
        /// </summary>
        public static string NextInstallmentDate {
            get {
                return ResourceManager.GetString("NextInstallmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalment.D.
        /// </summary>
        public static string NextInstallmentDateGrid {
            get {
                return ResourceManager.GetString("NextInstallmentDateGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Instalment Date.
        /// </summary>
        public static string NextInstallmentDateGridD {
            get {
                return ResourceManager.GetString("NextInstallmentDateGridD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Fee.
        /// </summary>
        public static string NotesFee {
            get {
                return ResourceManager.GetString("NotesFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payable Within Date.
        /// </summary>
        public static string PayableWithinDate {
            get {
                return ResourceManager.GetString("PayableWithinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Payment.
        /// </summary>
        public static string ReceivedPayment {
            get {
                return ResourceManager.GetString("ReceivedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string ReceivedPaymentGrid {
            get {
                return ResourceManager.GetString("ReceivedPaymentGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string RowVersion {
            get {
                return ResourceManager.GetString("RowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalment2.
        /// </summary>
        public static string SecondInstallment {
            get {
                return ResourceManager.GetString("SecondInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student#.
        /// </summary>
        public static string StudentNo {
            get {
                return ResourceManager.GetString("StudentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string TeacherPercentage {
            get {
                return ResourceManager.GetString("TeacherPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instalment3.
        /// </summary>
        public static string ThirdInstallment {
            get {
                return ResourceManager.GetString("ThirdInstallment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string Uid {
            get {
                return ResourceManager.GetString("Uid", resourceCulture);
            }
        }
    }
}
